--
-- PostgreSQL database dump
--

\restrict ajzwA2IxgNnk17kiOxCb3O2n5bHREaplJLa15uuLOutPbgPma0m8e97gAgIDska

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.questions VALUES (1, 2, 'What is an intelligent agent?', 'A database system', 'An entity that perceives its environment and takes actions', 'A programming language', 'A network protocol', 'B', 'easy', 'An intelligent agent perceives its environment through sensors and acts through actuators.', '2026-09-12 12:02:57.882001+05:30');
INSERT INTO public.questions VALUES (2, 2, 'Which property is important for a rational agent?', 'It always performs random actions', 'It chooses actions that maximize expected performance', 'It never observes its environment', 'It only performs predefined actions', 'B', 'medium', 'A rational agent chooses actions expected to maximize its performance measure.', '2026-09-12 12:02:57.882001+05:30');
INSERT INTO public.questions VALUES (3, 2, 'Which of the following is an example of an intelligent agent?', 'A thermostat', 'A calculator displaying a fixed result', 'A wall clock', 'A printed book', 'A', 'easy', 'A thermostat observes temperature and takes action to maintain the desired temperature.', '2026-09-12 12:02:57.882001+05:30');
INSERT INTO public.questions VALUES (4, 2, 'An intelligent agent must choose an action in an environment where the outcome of an action is uncertain. What should a rational agent primarily consider?', 'Only the most recent observation', 'The expected performance of possible actions', 'Only the number of available actions', 'Randomly selected actions', 'B', 'hard', 'A rational agent selects actions that maximize expected performance based on available information.', '2026-09-12 14:44:45.285068+05:30');
INSERT INTO public.questions VALUES (5, 2, 'Which situation best demonstrates the difference between a simple reflex agent and a model-based agent?', 'A thermostat turning on when temperature is low', 'A calculator performing arithmetic', 'A robot using its previous observations to reason about parts of the environment it cannot currently observe', 'A clock displaying the current time', 'C', 'hard', 'A model-based agent maintains an internal representation of the environment and can use previous observations.', '2026-09-12 14:44:45.285068+05:30');
INSERT INTO public.questions VALUES (6, 2, 'An autonomous delivery robot must select routes while considering traffic, battery level, delivery deadlines, and uncertain road conditions. Which characteristic of an intelligent agent is most important for this task?', 'Ability to maximize expected performance under changing conditions', 'Ability to perform only fixed predefined actions', 'Ability to ignore environmental observations', 'Ability to produce the same action for every situation', 'A', 'hard', 'An intelligent agent should perceive its environment and select actions that maximize expected performance under changing and uncertain conditions.', '2026-09-12 14:44:45.285068+05:30');
INSERT INTO public.questions VALUES (7, 1, 'What does AI stand for?', 'Artificial Intelligence', 'Automated Internet', 'Advanced Information', 'Artificial Integration', 'A', 'easy', 'AI stands for Artificial Intelligence, which focuses on creating systems that can perform tasks requiring human-like intelligence.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (8, 1, 'Which of the following is a common application of Artificial Intelligence?', 'Web page formatting', 'Voice assistants', 'File compression', 'Keyboard design', 'B', 'easy', 'Voice assistants use AI techniques such as speech recognition and natural language processing.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (9, 1, 'What is the main goal of Artificial Intelligence?', 'To replace all computers', 'To create systems capable of intelligent behavior', 'To increase internet speed', 'To store more files', 'B', 'easy', 'AI aims to develop systems that can perform tasks involving abilities such as reasoning, learning, perception, and decision-making.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (10, 1, 'Which ability is commonly associated with an intelligent AI system?', 'Learning from data', 'Only storing files', 'Only displaying text', 'Only performing arithmetic', 'A', 'medium', 'Learning from data allows AI systems to improve their predictions or decisions based on experience.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (11, 1, 'Which field of AI focuses on enabling computers to understand human language?', 'Computer Graphics', 'Natural Language Processing', 'Operating Systems', 'Database Management', 'B', 'medium', 'Natural Language Processing, or NLP, enables computers to process and understand human language.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (12, 1, 'Which approach allows an AI system to improve its performance using experience or data?', 'Machine Learning', 'Computer Formatting', 'File Management', 'Network Cabling', 'A', 'medium', 'Machine Learning allows systems to learn patterns from data and improve their performance without explicitly programming every rule.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (13, 1, 'An AI system observes its environment, makes decisions, and takes actions to achieve a goal. Which concept best describes this system?', 'Database', 'Intelligent agent', 'Compiler', 'Operating system', 'B', 'hard', 'An intelligent agent perceives its environment, makes decisions, and performs actions to achieve specified goals.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (14, 1, 'Why is reasoning important in Artificial Intelligence?', 'It allows systems to make decisions based on available information', 'It increases monitor resolution', 'It reduces keyboard size', 'It replaces computer hardware', 'A', 'hard', 'Reasoning allows an AI system to draw conclusions and make decisions from available information and knowledge.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (15, 1, 'Which statement best describes the relationship between Artificial Intelligence and Machine Learning?', 'AI and Machine Learning are completely unrelated', 'Machine Learning is one approach used to achieve Artificial Intelligence', 'AI is a subset of Machine Learning', 'Machine Learning only deals with computer hardware', 'B', 'hard', 'Machine Learning is a major approach within AI that enables systems to learn patterns from data and improve performance.', '2026-09-13 08:58:59.921822+05:30');
INSERT INTO public.questions VALUES (16, 3, 'What does BFS stand for?', 'Binary First Search', 'Breadth First Search', 'Basic First Search', 'Breadth Fast Search', 'B', 'easy', 'BFS stands for Breadth First Search. It explores nodes level by level.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (17, 3, 'Which data structure is commonly used in BFS?', 'Stack', 'Queue', 'Heap', 'Array', 'B', 'easy', 'BFS uses a queue because nodes are explored in the order they are discovered.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (18, 3, 'How does BFS explore a graph?', 'Depth by depth', 'Level by level', 'Randomly', 'Only from the last node', 'B', 'easy', 'BFS visits nodes level by level, starting from the source node.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (19, 3, 'What is BFS commonly used for in an unweighted graph?', 'Finding the shortest path', 'Sorting numbers', 'Compressing files', 'Generating random numbers', 'A', 'medium', 'BFS can find the shortest path in an unweighted graph because it explores nodes level by level.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (20, 3, 'What is the time complexity of BFS using an adjacency list?', 'O(V)', 'O(E)', 'O(V + E)', 'O(V x E)', 'C', 'medium', 'With an adjacency list, BFS visits each vertex and edge at most once, giving O(V + E).', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (21, 3, 'Which structure stores vertices waiting to be explored in BFS?', 'Queue', 'Stack', 'Tree', 'Hash table', 'A', 'medium', 'A queue stores discovered vertices that are waiting to be processed.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (22, 3, 'Why does BFS find the shortest path in an unweighted graph?', 'It always chooses the largest edge', 'It explores vertices according to their distance from the source', 'It uses recursion', 'It visits vertices randomly', 'B', 'hard', 'BFS explores all vertices at distance 1, then distance 2, and so on. Therefore the first time a vertex is reached gives its shortest distance.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (23, 3, 'What is the space complexity of BFS in the worst case?', 'O(1)', 'O(log V)', 'O(V)', 'O(Eý)', 'C', 'hard', 'The queue and visited information can require O(V) space.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (24, 3, 'In BFS, what happens when a newly discovered vertex is found?', 'It is immediately removed', 'It is added to the queue', 'It is added to a stack', 'It is ignored', 'B', 'hard', 'An undiscovered vertex is marked as visited and added to the BFS queue for later processing.', '2026-09-13 10:16:27.035896+05:30');
INSERT INTO public.questions VALUES (25, 4, 'What does DFS stand for?', 'Depth First Search', 'Data First Search', 'Direct First Search', 'Depth Fast Search', 'A', 'easy', 'DFS stands for Depth First Search. It explores as far as possible along one branch before backtracking.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (26, 4, 'Which data structure is commonly used to implement DFS?', 'Queue', 'Stack', 'Heap', 'Hash table', 'B', 'easy', 'DFS commonly uses a stack, either explicitly or through recursion.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (27, 4, 'How does DFS explore a graph?', 'Level by level', 'Randomly', 'As deep as possible before backtracking', 'Only the starting node', 'C', 'easy', 'DFS explores one path as deeply as possible before backtracking to explore another path.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (28, 4, 'Which technique can be used to implement DFS?', 'Recursion', 'Binary search', 'Hashing', 'Sorting', 'A', 'medium', 'DFS can be implemented using recursion because the call stack naturally behaves like a stack.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (29, 4, 'What is the time complexity of DFS using an adjacency list?', 'O(V + E)', 'O(VýE)', 'O(log V)', 'O(1)', 'A', 'medium', 'DFS visits each vertex and edge at most once, resulting in O(V + E) time.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (30, 4, 'Which data structure is explicitly used in iterative DFS?', 'Queue', 'Stack', 'Priority queue', 'Linked list only', 'B', 'medium', 'Iterative DFS uses a stack to keep track of vertices that need to be explored.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (31, 4, 'What is one major difference between BFS and DFS?', 'BFS uses a queue while DFS uses a stack', 'BFS always uses recursion', 'DFS always finds the shortest path', 'There is no difference', 'A', 'hard', 'BFS generally explores level by level using a queue, while DFS explores deeply using a stack or recursion.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (32, 4, 'Can DFS be used to detect cycles in a graph?', 'Yes', 'No', 'Only in arrays', 'Only in sorted graphs', 'A', 'hard', 'DFS can be used for cycle detection by tracking visited nodes and the current traversal path.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (33, 4, 'Why does DFS backtrack?', 'To explore previously unvisited branches', 'To delete visited nodes', 'To increase the graph size', 'To sort the vertices', 'A', 'hard', 'After reaching a point where no unvisited neighbor remains, DFS backtracks to an earlier vertex and explores another branch.', '2026-09-13 10:21:21.902547+05:30');
INSERT INTO public.questions VALUES (34, 5, 'What does A* search use to find a path?', 'Only the path cost', 'Only a heuristic', 'Path cost and heuristic', 'Random selection', 'C', 'easy', 'A* combines the actual path cost with a heuristic estimate.', '2026-09-13 10:47:55.179681+05:30');
INSERT INTO public.questions VALUES (35, 5, 'Which formula is used by A* search?', 'f(n) = g(n) + h(n)', 'f(n) = g(n) - h(n)', 'f(n) = g(n) * h(n)', 'f(n) = h(n) / g(n)', 'A', 'easy', 'A* calculates f(n) as g(n) plus h(n).', '2026-09-13 10:47:55.179681+05:30');
INSERT INTO public.questions VALUES (36, 5, 'What does h(n) represent in A* search?', 'Cost from start to current node', 'Estimated cost from current node to goal', 'Total number of nodes', 'Number of visited nodes', 'B', 'easy', 'h(n) is the heuristic estimate of the remaining cost to the goal.', '2026-09-13 10:47:55.179681+05:30');
INSERT INTO public.questions VALUES (37, 5, 'What does g(n) represent in A* search?', 'Heuristic estimate', 'Estimated total cost', 'Actual cost from start to current node', 'Number of graph edges', 'C', 'medium', 'g(n) represents the actual path cost from the starting node to the current node.', '2026-09-13 10:48:02.832389+05:30');
INSERT INTO public.questions VALUES (38, 5, 'What is the purpose of a heuristic in A*?', 'Estimate the remaining cost to the goal', 'Remove all nodes', 'Increase memory usage', 'Randomly select nodes', 'A', 'medium', 'The heuristic estimates the remaining cost to the goal.', '2026-09-13 10:48:02.832389+05:30');
INSERT INTO public.questions VALUES (39, 5, 'When is A* guaranteed to find an optimal path?', 'When the heuristic is admissible', 'When the graph has no nodes', 'When the heuristic always overestimates', 'When nodes are selected randomly', 'A', 'medium', 'An admissible heuristic does not overestimate the actual remaining cost.', '2026-09-13 10:48:02.832389+05:30');
INSERT INTO public.questions VALUES (40, 5, 'What happens when h(n) is zero for every node?', 'A* behaves like DFS', 'A* behaves like BFS', 'A* behaves like Dijkstra algorithm', 'A* stops immediately', 'C', 'hard', 'When h(n) is zero, f(n) equals g(n), so A* behaves like uniform-cost search or Dijkstra algorithm.', '2026-09-13 10:48:10.776476+05:30');
INSERT INTO public.questions VALUES (41, 5, 'Why can an accurate heuristic improve A* performance?', 'It prioritizes nodes likely to lead toward the goal', 'It increases unnecessary nodes', 'It removes the goal node', 'It disables path costs', 'A', 'hard', 'A good heuristic guides the search toward promising paths and reduces unnecessary exploration.', '2026-09-13 10:48:10.776476+05:30');
INSERT INTO public.questions VALUES (42, 5, 'What is a major advantage of A* over uninformed search?', 'It uses knowledge about the goal to guide the search', 'It never uses memory', 'It always explores every node', 'It does not calculate path costs', 'A', 'hard', 'A* uses heuristic information about the goal to guide its search.', '2026-09-13 10:48:10.776476+05:30');
INSERT INTO public.questions VALUES (43, 5, 'In the A* search algorithm, how is the total estimated cost f(n) of a path through a node n calculated?', 'f(n) = g(n) + h(n), where g(n) is the cost from the start and h(n) is the estimated cost to the goal', 'f(n) = g(n) * h(n), where both values represent the total number of visited nodes', 'f(n) = h(n) - g(n), where g(n) is the remaining distance to the goal', 'f(n) = g(n) / h(n), where h(n) is the time taken to reach the node', 'A', 'easy', 'A* search evaluates nodes using f(n) = g(n) + h(n), combining the actual cost from the start node g(n) with the estimated heuristic cost to the goal h(n).', '2026-09-13 14:47:12.259961+05:30');
INSERT INTO public.questions VALUES (44, 5, 'What does it mean for a heuristic function h(n) in A* search to be ''admissible''?', 'It always overestimates the actual cost to reach the goal', 'It never overestimates the actual cost to reach the goal', 'It calculates the exact cost with zero error every time', 'It selects path options at random to prevent infinite loops', 'B', 'easy', 'A heuristic is admissible if it never overestimates the true cost to reach the goal, which guarantees that A* search finds an optimal (shortest) path.', '2026-09-13 14:47:12.259961+05:30');
INSERT INTO public.questions VALUES (45, 5, 'When deciding which node to expand next, which node will the A* search algorithm select from the fringe (open list)?', 'The node that was added to the list most recently', 'The node with the highest estimated total cost f(n)', 'The node with the lowest estimated total cost f(n)', 'A randomly chosen node from the list', 'C', 'easy', 'A* search prioritizes exploration by always expanding the node with the lowest f(n) value, as it represents the most promising path toward the goal.', '2026-09-13 14:47:12.259961+05:30');
INSERT INTO public.questions VALUES (46, 5, 'In the A* search evaluation function f(n) = g(n) + h(n), what does g(n) represent?', 'The estimated cost from the current node n to the goal node.', 'The actual cost incurred to reach node n from the start node.', 'The total estimated cost of the optimal path through node n.', 'The total number of edges connected to node n.', 'B', 'easy', 'In A* search, g(n) is the exact path cost spent to travel from the starting node to the current node n, while h(n) is the estimated cost from node n to the goal.', '2026-09-13 15:04:35.312823+05:30');
INSERT INTO public.questions VALUES (47, 5, 'How does the A* search algorithm choose which node to expand next?', 'It picks the node with the highest estimated heuristic cost h(n).', 'It picks the node that was added to the open set most recently.', 'It picks the node with the lowest total evaluation cost f(n).', 'It randomly picks any node from the unvisited set.', 'C', 'easy', 'A* search prioritizes nodes based on f(n) = g(n) + h(n) and always expands the node with the lowest f(n) value first.', '2026-09-13 15:04:35.312823+05:30');
INSERT INTO public.questions VALUES (48, 5, 'What does it mean for a heuristic function h(n) in A* search to be ''admissible''?', 'It never overestimates the true cost to reach the goal.', 'It always returns a negative number for non-goal nodes.', 'It calculates the exact distance without using any estimates.', 'It equals zero for every node in the search space.', 'A', 'easy', 'A heuristic is admissible if it never overestimates the cost to reach the goal, which guarantees that A* search will find the optimal path.', '2026-09-13 15:04:35.312823+05:30');
INSERT INTO public.questions VALUES (49, 6, 'An unauthorized user gains access to a company''s private customer database and views sensitive personal information. Which pillar of the CIA Triad has been directly breached?', 'Confidentiality', 'Integrity', 'Availability', 'Authenticity', 'A', 'easy', 'Confidentiality ensures that sensitive information is accessible only to authorized individuals. Viewing private data without permission violates confidentiality.', '2026-09-13 15:11:44.211607+05:30');
INSERT INTO public.questions VALUES (50, 6, 'An attacker secretly changes account balances in a bank database. Which principle of the CIA Triad is violated by this unauthorized data modification?', 'Availability', 'Confidentiality', 'Integrity', 'Accountability', 'C', 'easy', 'Integrity ensures that data remains accurate, complete, and protected from unauthorized modification or tampering.', '2026-09-13 15:11:44.211607+05:30');
INSERT INTO public.questions VALUES (51, 6, 'A cyberattack floods a school server with junk traffic, preventing students from logging in to access their online exams. Which component of the CIA Triad is primarily affected?', 'Confidentiality', 'Availability', 'Integrity', 'Non-repudiation', 'B', 'easy', 'Availability ensures that systems, networks, and data are accessible to authorized users when needed.', '2026-09-13 15:11:44.211607+05:30');
INSERT INTO public.questions VALUES (52, 6, 'A company encrypts its sensitive customer records so that only authorized employees can read them. Which component of the CIA Triad is being directly protected?', 'Confidentiality', 'Integrity', 'Availability', 'Authenticity', 'A', 'easy', 'Confidentiality ensures that sensitive information is kept secret and accessible only to authorized individuals.', '2026-09-13 15:11:57.667464+05:30');
INSERT INTO public.questions VALUES (53, 6, 'An attacker secretly changes a user''s account balance in a database without permission. Which principle of the CIA Triad has been violated?', 'Availability', 'Confidentiality', 'Integrity', 'Accountability', 'C', 'easy', 'Integrity ensures that data remains accurate, complete, and protected from unauthorized modification or tampering.', '2026-09-13 15:11:57.667464+05:30');
INSERT INTO public.questions VALUES (54, 6, 'A Denial of Service (DoS) attack overwhelms an online store''s web server, causing the website to crash and preventing customers from visiting. Which pillar of the CIA Triad is primarily affected?', 'Confidentiality', 'Integrity', 'Non-repudiation', 'Availability', 'D', 'easy', 'Availability ensures that systems, networks, and data are accessible to authorized users whenever they need them.', '2026-09-13 15:11:57.667464+05:30');
INSERT INTO public.questions VALUES (55, 7, 'An employee receives an email that appears to be from their bank, asking them to click a link and enter their login credentials. What type of attack is this?', 'Phishing', 'Ransomware', 'Denial of Service (DoS)', 'Man-in-the-Middle', 'A', 'easy', 'Phishing is a cyber attack where attackers pretend to be reputable organizations to trick individuals into providing sensitive information.', '2026-09-13 15:18:16.438178+05:30');
INSERT INTO public.questions VALUES (56, 7, 'A computer user finds that all their personal files have been locked, and a pop-up message demands payment to unlock them. What type of cyber attack is being used?', 'Spyware', 'Ransomware', 'Phishing', 'SQL Injection', 'B', 'easy', 'Ransomware is malicious software that encrypts or locks a target''s files and demands a ransom payment to restore access.', '2026-09-13 15:18:16.438178+05:30');
INSERT INTO public.questions VALUES (57, 7, 'A website becomes completely unavailable because thousands of automated requests overload its servers at the same time. Which type of attack is described?', 'Password Attack', 'Ransomware', 'Denial of Service (DoS)', 'Spyware', 'C', 'easy', 'A Denial of Service (DoS) attack overwhelms a system with excessive traffic to make it unavailable to legitimate users.', '2026-09-13 15:18:16.438178+05:30');
INSERT INTO public.questions VALUES (58, 7, 'An employee receives an urgent email that appears to come from their company''s IT department, asking them to click a link and re-enter their password. What type of cyber attack does this describe?', 'Phishing', 'Ransomware', 'Denial of Service', 'Eavesdropping', 'A', 'easy', 'Phishing is an attack where scammers trick people into revealing sensitive information, such as passwords, by posing as a trustworthy source in emails or messages.', '2026-09-13 15:18:30.977845+05:30');
INSERT INTO public.questions VALUES (59, 7, 'A user downloads an unknown software file. Shortly after, all their photos and documents are locked, and a message appears requesting payment to unlock them. What type of attack is this?', 'Spyware', 'Ransomware', 'Phishing', 'SQL Injection', 'B', 'easy', 'Ransomware is malicious software that encrypts a victim''s files and demands a ransom payment to restore access to them.', '2026-09-13 15:18:30.977845+05:30');
INSERT INTO public.questions VALUES (60, 7, 'A popular online store becomes unreachable during a major sale because thousands of compromised computers flood the website with fake traffic at the same time. What type of attack is happening?', 'Distributed Denial of Service (DDoS)', 'Phishing', 'Keylogging', 'Man-in-the-Middle', 'A', 'easy', 'A Distributed Denial of Service (DDoS) attack overwhelms a target server or network with a flood of internet traffic from multiple sources, making it unavailable to real users.', '2026-09-13 15:18:30.977845+05:30');
INSERT INTO public.questions VALUES (61, 8, 'Which network security device monitors incoming and outgoing traffic to block unauthorized access based on defined security rules?', 'Firewall', 'Network Interface Card', 'Hub', 'Uninterruptible Power Supply', 'A', 'easy', 'A firewall acts as a security barrier that filters incoming and outgoing network traffic based on established security rules to prevent unauthorized access.', '2026-09-13 15:26:07.883259+05:30');
INSERT INTO public.questions VALUES (62, 8, 'Why is HTTPS preferred over HTTP when entering sensitive information like passwords on a website?', 'HTTPS increases the Internet connection speed.', 'HTTPS encrypts data during transmission so unauthorized users cannot read it.', 'HTTPS stores a copy of your credentials on your local network.', 'HTTPS prevents physical damage to the web server.', 'B', 'easy', 'HTTPS uses encryption to secure the communication channel between your browser and the web server, protecting sensitive data from eavesdroppers.', '2026-09-13 15:26:07.883259+05:30');
INSERT INTO public.questions VALUES (63, 8, 'An employee receives an urgent email claiming to be from their bank asking them to click a link and re-verify their login details. What type of security threat is this?', 'Distributed Denial of Service (DDoS)', 'Phishing attack', 'SQL Injection', 'Buffer Overflow', 'B', 'easy', 'Phishing is a social engineering attack where malicious actors pose as trustworthy entities to trick individuals into revealing sensitive information.', '2026-09-13 15:26:07.883259+05:30');
INSERT INTO public.questions VALUES (64, 8, 'A company wants to monitor and control incoming and outgoing network traffic based on predetermined security rules. Which tool should they use?', 'Network Switch', 'Firewall', 'Modem', 'Repeater', 'B', 'easy', 'A firewall acts as a barrier that inspects incoming and outgoing network traffic to block unauthorized access based on defined security rules.', '2026-09-13 15:26:19.231299+05:30');
INSERT INTO public.questions VALUES (65, 8, 'Why is HTTPS preferred over standard HTTP when transmitting sensitive information like passwords across the internet?', 'HTTPS speeds up network connection speeds.', 'HTTPS encrypts data sent between the user''s browser and the web server.', 'HTTPS prevents web servers from storing any user data.', 'HTTPS automatically generates complex passwords for the user.', 'B', 'easy', 'HTTPS uses encryption protocols to protect data in transit, ensuring that intercepted traffic cannot easily be read by unauthorized third parties.', '2026-09-13 15:26:19.231299+05:30');
INSERT INTO public.questions VALUES (66, 8, 'What primary security benefit does a Virtual Private Network (VPN) offer when connecting to an unsecured public Wi-Fi network?', 'It increases the physical range of the device''s Wi-Fi receiver.', 'It creates an encrypted tunnel to protect network traffic from eavesdroppers.', 'It automatically removes existing malware from the connected device.', 'It permanently blocks all advertisements on every visited website.', 'B', 'easy', 'A VPN secures internet traffic by creating an encrypted tunnel between the user''s device and a remote server, hiding data from potential attacker on the same Wi-Fi network.', '2026-09-13 15:26:19.231299+05:30');
INSERT INTO public.questions VALUES (67, 6, 'A company encrypts its private customer database so that only authorized staff can view the sensitive information. Which CIA Triad principle is being applied?', 'Confidentiality', 'Integrity', 'Availability', 'Authenticity', 'A', 'easy', 'Confidentiality ensures that sensitive data is accessible only to authorized users and protected from unauthorized viewing.', '2026-09-13 16:36:24.782908+05:30');
INSERT INTO public.questions VALUES (68, 6, 'During a data transfer, an unauthorized user modifies a file to change financial figures before it reaches the recipient. Which CIA Triad principle was breached?', 'Confidentiality', 'Integrity', 'Availability', 'Accountability', 'B', 'easy', 'Integrity ensures that data remains accurate, complete, and unaltered by unauthorized parties during storage or transmission.', '2026-09-13 16:36:24.782908+05:30');
INSERT INTO public.questions VALUES (69, 6, 'A cyberattack causes an online shopping website to crash, preventing legitimate users from accessing their accounts and placing orders. Which CIA Triad principle is directly affected?', 'Confidentiality', 'Integrity', 'Availability', 'Non-repudiation', 'C', 'easy', 'Availability ensures that services, systems, and data remain accessible to authorized users whenever they need them.', '2026-09-13 16:36:24.782908+05:30');
INSERT INTO public.questions VALUES (70, 1, 'Which of the following best describes the core functionality of a rational AI agent?', 'It performs actions using hardcoded rules that cannot change over time.', 'It perceives its environment through sensors and takes actions that maximize its expected success.', 'It mimics human emotional responses to build empathy with users.', 'It guarantees 100% accuracy in every decision, regardless of environmental uncertainty.', 'B', 'medium', 'A rational AI agent operates by perceiving its environment through sensors and choosing actions that maximize its performance measure based on its goal and percept sequence.', '2026-09-13 16:40:31.381391+05:30');
INSERT INTO public.questions VALUES (71, 1, 'A modern voice assistant can transcribe speech, manage schedules, and control smart devices, but it cannot transfer its skills to diagnose medical conditions or drive a car. How is this system classified?', 'Artificial General Intelligence (AGI)', 'Artificial Narrow Intelligence (ANI)', 'Artificial Superintelligence (ASI)', 'Autonomous General Agent', 'B', 'medium', 'Artificial Narrow Intelligence (ANI), also known as Weak AI, is designed and trained for specific tasks and lacks general cognitive abilities across unrelated domains.', '2026-09-13 16:40:31.381391+05:30');
INSERT INTO public.questions VALUES (72, 1, 'In AI problem-solving, what is the primary benefit of using a heuristic search algorithm over an uninformed (blind) search algorithm?', 'It uses domain-specific knowledge to guide the search, drastically reducing the search space.', 'It eliminates the need for defining a goal state before searching.', 'It guarantees that the algorithm operates with zero memory overhead.', 'It replaces search trees with deep neural network training.', 'A', 'medium', 'Heuristic search algorithms use extra domain knowledge (heuristics) to estimate the distance to the goal, allowing them to prioritize promising paths and explore fewer states than blind search methods.', '2026-09-13 16:40:31.381391+05:30');
INSERT INTO public.questions VALUES (73, 6, 'An employee encrypts a sensitive company document before sending it over the internet to prevent unauthorized people from reading it. Which principle of the CIA Triad does this action primarily support?', 'Confidentiality', 'Integrity', 'Availability', 'Non-repudiation', 'A', 'easy', 'Confidentiality ensures that sensitive information is accessible only to authorized users and hidden from unauthorized individuals.', '2026-09-13 16:46:43.426353+05:30');
INSERT INTO public.questions VALUES (74, 6, 'A bank uses digital signatures to verify that a transaction amount has not been modified or tampered with during transfer. Which CIA Triad component is being enforced?', 'Availability', 'Integrity', 'Confidentiality', 'Authorization', 'B', 'easy', 'Integrity ensures that data remains accurate, complete, and untampered with by unauthorized parties.', '2026-09-13 16:46:43.426353+05:30');
INSERT INTO public.questions VALUES (75, 6, 'An e-commerce company uses backup power generators and redundant servers to keep its website running smoothly during unexpected power outages. Which element of the CIA Triad does this best represent?', 'Confidentiality', 'Authenticity', 'Availability', 'Integrity', 'C', 'easy', 'Availability ensures that systems, services, and data are accessible to authorized users whenever they are needed.', '2026-09-13 16:46:43.426353+05:30');
INSERT INTO public.questions VALUES (76, 2, 'Which of the following best describes how an intelligent agent interacts with its environment?', 'It perceives its environment through sensors and acts upon it using actuators.', 'It relies entirely on human operators to make every decision.', 'It ignores environmental data and acts based purely on random choices.', 'It only stores data without ever taking actions or making decisions.', 'A', 'easy', 'An intelligent agent interacts with its environment by gathering information through sensors and taking actions to achieve its goals using actuators.', '2026-09-16 16:22:13.377017+05:30');
INSERT INTO public.questions VALUES (77, 2, 'An automated robot uses a camera to detect an obstacle and uses its motorized wheels to steer away from it. In the context of an intelligent agent, what role do the motorized wheels play?', 'Sensors', 'Actuators', 'Environments', 'Percept sequences', 'B', 'easy', 'Actuators are the mechanisms an intelligent agent uses to take actions and affect its environment, such as motors, wheels, or robotic arms.', '2026-09-16 16:22:22.332719+05:30');


--
-- Data for Name: subjects; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.subjects VALUES (1, 'Artificial Intelligence', 'Fundamentals of AI,intelligent agents,search algorithms and machine learning.', '2026-09-12 11:43:33.758603+05:30');
INSERT INTO public.subjects VALUES (2, 'Cybersecurity', 'Fundamentals of cybersecurity,threats,vulnerabilities and security concepts.', '2026-09-12 11:43:33.758603+05:30');
INSERT INTO public.subjects VALUES (3, 'Computer Networks', 'Networking fundamentals,protocols,communication and network security.', '2026-09-12 11:43:33.758603+05:30');
INSERT INTO public.subjects VALUES (4, 'Python Programming', 'Python Programming fundamentalas,data structures and problem solving.', '2026-09-12 11:43:33.758603+05:30');
INSERT INTO public.subjects VALUES (5, 'Mathematics', 'Mathematics for school students', '2026-09-14 07:16:58.055203+05:30');
INSERT INTO public.subjects VALUES (6, 'Physics', 'Physics for school students', '2026-09-14 07:16:58.055203+05:30');
INSERT INTO public.subjects VALUES (7, 'Chemistry', 'Chemistry for school students', '2026-09-14 07:16:58.055203+05:30');
INSERT INTO public.subjects VALUES (8, 'Biology', 'Biology for school students', '2026-09-14 07:16:58.055203+05:30');
INSERT INTO public.subjects VALUES (9, 'English', 'English language and communication', '2026-09-14 07:16:58.055203+05:30');
INSERT INTO public.subjects VALUES (10, 'Social Science', 'Social science fundamentals', '2026-09-14 07:16:58.055203+05:30');
INSERT INTO public.subjects VALUES (11, 'Computer Science', 'Computer science fundamentals', '2026-09-14 07:16:58.055203+05:30');
INSERT INTO public.subjects VALUES (14, 'Data Structures', 'Data structures and algorithms', '2026-09-14 07:18:07.679872+05:30');
INSERT INTO public.subjects VALUES (15, 'Machine Learning', 'Machine learning fundamentals', '2026-09-14 07:18:07.679872+05:30');
INSERT INTO public.subjects VALUES (16, 'Database Management Systems', 'Database concepts and SQL', '2026-09-14 07:18:07.679872+05:30');
INSERT INTO public.subjects VALUES (17, 'Operating Systems', 'Operating system concepts', '2026-09-14 07:18:07.679872+05:30');
INSERT INTO public.subjects VALUES (18, 'Software Engineering', 'Software engineering principles', '2026-09-14 07:18:07.679872+05:30');
INSERT INTO public.subjects VALUES (19, 'Web Development', 'Modern web development', '2026-09-14 07:18:07.679872+05:30');


--
-- Data for Name: topics; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.topics VALUES (1, 1, 'Introduction to Artificial Intelligence', 'Basics of AI and intelligent systems.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (2, 1, 'Intelligent Agents', 'Agents, environments, rationality and agent types.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (3, 1, 'Breadth First Search', 'Uninformed search using breadth first search.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (4, 1, 'Depth First Search', 'Uninformed search using depth first search.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (5, 1, 'A* Search', 'Heuristic search using A star algorithm.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (6, 2, 'CIA Triad', 'Confidentiality, Integrity and Availability.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (7, 2, 'Types of Cyber Attacks', 'Common cyber attacks and their characteristics.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (8, 2, 'Network Security', 'Basic concepts of securing computer networks.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (9, 2, 'Risk Assessment', 'Identifying and managing cybersecurity risks.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (10, 3, 'OSI Model', 'Seven-layer OSI networking model.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (11, 3, 'TCP/IP Model', 'Internet protocol architecture.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (12, 3, 'Data Link Layer', 'Framing, error detection and flow control.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (13, 4, 'Python Basics', 'Variables, data types and basic syntax.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (14, 4, 'Python Control Flow', 'Conditions, loops and program control.', '2026-09-12 11:48:59.430872+05:30');
INSERT INTO public.topics VALUES (15, 4, 'Python Functions', 'Creating and using functions in Python.', '2026-09-12 11:48:59.430872+05:30');


--
-- Name: questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.questions_id_seq', 77, true);


--
-- Name: subjects_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subjects_id_seq', 19, true);


--
-- Name: topics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.topics_id_seq', 15, true);


--
-- PostgreSQL database dump complete
--

\unrestrict ajzwA2IxgNnk17kiOxCb3O2n5bHREaplJLa15uuLOutPbgPma0m8e97gAgIDska

